/*
Copyright 2014 JWACK APPS
All rights reserved
jwackapps.com
Created by Andrew B. Kiger
ajkiger@gmail.com
*/


eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('l 6(){3.p=2;3.m=2;3.v=2;3.G=2;3.H=2;3.w=2;3.x=2;3.q=2;3.r=2;3.s=2;3.y=2;3.z=2;3.8=2;3.A=2};6.7.p=2;6.7.m=2;6.7.v=2;6.7.G=2;6.7.H=2;6.7.w=2;6.7.x=2;6.7.q=2;6.7.r=2;6.7.s=2;6.7.y=2;6.7.z=2;6.7.8=2;6.7.A=2;6.7.S=l(){3.w=I J();3.x=I J();3.q=k;3.r=k;3.s=k;3.y=k;3.z=k;3.8=k;3.A=k};l T(a){5 b=" - ";n(5 i=0;i<a.o;i++){5 c=a[i];9(!c.8){b=b+c.p+" - "}}B.C(\'U\').D="V: "+b}l W(a){5 b=" - ";n(5 i=0;i<a.o;i++){5 c=a[i];9(!c.8){b=b+c.p+" - "}}B.C(\'X\').D="Y: "+b}l Z(f){5 g=" ";5 h;5 j=$("#K");j.L("M","10","N",l(){9(!t.O){n(5 i=0;i<f.o;i++){h=f[i];9(!h.r&&!h.8){h.r=u;g=g+h.m+" &4&4&4&4&4 "}P 9(h.q&&!h.s&&!h.8){h.s=u}P 9(!h.q&&!h.8){g=g+h.m+" &4&4&4&4&4 "}}9(g===" "){5 a=" &4&4 ";n(5 i=0;i<f.o;i++){h=f[i];9(!h.8){a=a+h.m+" &4&4&4&4&4 "}}5 b=k;n(5 i=0;i<f.o;i++){h=f[i];9(h.8){h.8=k;b=u;5 c=h.p.11(0,1);5 d=h.v;g="12 13 14 15 E 16 "+" \\""+c+"\\""+"<F>"+"17 18 "+d+" 19 1a."+"<F>"+"1b 1c 1d E 1e 1f E 1g 1h:"+"<F>"+a;1i}}9(!b){t.Q=u;R(1j);R(1k)}}}9(t.Q||t.1l||t.O){g=g=" ";n(5 i=0;i<f.o;i++){5 e=f[i];g=g+e.m+" &4&4&4&4&4 "}}B.C(\'K\').D=g});j.1m({L:"M",1n:N})}',62,86,'||null|this|nbsp|var|WordListObject|prototype|alphabetQuestHiddenWord|if|||||||||||false|function|wordDisplayName|for|length|wordName|wordFound|wordPlacedScrollView|wordStrikedScrollView|sceneController|true|wordLength|allLetters|allSquares|wordHint|messageDisplayed|hideHiddenWord|document|getElementById|innerHTML|the|br|firstLetterSquare|lastLetterSquare|new|Array|wordbox|effect|fade|300|solveCube|else|gameOver|clearTimeout|init|UpdateTextAreaViewX|xcoord|Post|UpdateTextAreaViewY|ycoord|Pre|UpdateTextAreaView|swing|substring|Hidden|word|begins|with|letter|and|is|letters|long|It|will|match|theme|of|following|words|break|starTimer1|starTimer2|giveUpOnHiddenWord|show|duration'.split('|'),0,{}))