/*
Copyright 2014 JWACK APPS
All rights reserved
jwackapps.com
Created by Andrew B. Kiger
ajkiger@gmail.com
*/


eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('l 5(){3.t=2;3.k=2;3.u=2;3.F=2;3.G=2;3.v=2;3.w=2;3.m=2;3.n=2;3.o=2;3.x=2;3.y=2;3.9=2;3.z=2};5.6.t=2;5.6.k=2;5.6.u=2;5.6.F=2;5.6.G=2;5.6.v=2;5.6.w=2;5.6.m=2;5.6.n=2;5.6.o=2;5.6.x=2;5.6.y=2;5.6.9=2;5.6.z=2;5.6.N=l(){3.v=H I();3.w=H I();3.m=j;3.n=j;3.o=j;3.x=j;3.y=j;3.9=j;3.z=j};l O(a){8(P){A(a)}B{J.Q(C);R(l(){A(a);J.S(C)},C)}}l A(a){7 b=" ";7 c;8(!p.K){q(7 i=0;i<a.r;i++){c=a[i];8(!c.n&&!c.9){c.n=s;b=b+c.k+" &4&4&4&4&4 "}B 8(c.m&&!c.o&&!c.9){c.o=s}B 8(!c.m&&!c.9){b=b+c.k+" &4&4&4&4&4 "}}8(b===" "){7 d=" &4&4 ";q(7 i=0;i<a.r;i++){c=a[i];8(!c.9){d=d+c.k+" &4&4&4&4&4 "}}7 e=j;q(7 i=0;i<a.r;i++){c=a[i];8(c.9){c.9=j;e=s;7 f=c.t.T(0,1);7 g=c.u;b="U V W X D Y"+"<E>"+" \\""+f+"\\""+" Z 10 "+g+" 11 12."+"<E>"+"13 14 15 D 16 17 D 18 19:"+"<E>"+d;1a}}8(!e){p.L=s;M(1b);M(1c)}}}8(p.L||p.1d||p.K){b=b=" ";q(7 i=0;i<a.r;i++){7 h=a[i];b=b+h.k+" &4&4&4&4&4 "}}1e.1f=b}',62,78,'||null|this|nbsp|WordListObject|prototype|var|if|alphabetQuestHiddenWord||||||||||false|wordDisplayName|function|wordFound|wordPlacedScrollView|wordStrikedScrollView|sceneController|for|length|true|wordName|wordLength|allLetters|allSquares|wordHint|messageDisplayed|hideHiddenWord|executeUpdate|else|300|the|br|firstLetterSquare|lastLetterSquare|new|Array|tempWd|solveCube|gameOver|clearTimeout|init|UpdateTextAreaView|isiOSMobile|fadeOut|setTimeout|fadeIn|substring|Hidden|word|begins|with|letter|and|is|letters|long|It|will|match|theme|of|following|words|break|starTimer1|starTimer2|giveUpOnHiddenWord|tempWdX|innerHTML'.split('|'),0,{}))